[package]
name = "Launchpad"
version = "1.0.0"
published-at = "0xa0a588a75179d51d60e4b8575a3a89322552166840de14d3d3367efd624dc0fc"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.33.0
rev = "c525ba6489261ff6db65e87bf9a3fdda0a6c7be3"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.33.0
rev = "38743a3700abf8577a17e2751e82a4c0c249dfb3"

[dependencies.Request]
local = "./../request"

[dependencies.Kiosk]
local = "./../kiosk"

[addresses]
ob_launchpad = "0xa0a588a75179d51d60e4b8575a3a89322552166840de14d3d3367efd624dc0fc"
