[package]
name = "NftProtocol"
version = "0.18.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.21.0
rev = "2d709054a08d904b9229a2472af679f210af3827"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.22.0
rev = "271a3edd4571055c83ac08fd920b03e4f36e1241"

[addresses]
nft_protocol = "0x"
