[package]
name = "NftProtocol"
version = "0.10.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.16.0
rev = "6c001d0c491d1481fd4b477881d320e2421a6517"

[dependencies.Movemate]
git = "https://github.com/Origin-Byte/movemate.git"
subdir = "sui"
# devnet-0.16.0
rev = "abb5e275bfd96b4f51ebc68da2cff7d36140b1c6"

[addresses]
nft_protocol = "0x0"
