[package]
name = "Suitraders"
version = "0.28.0"
published-at = "0x7e63f9bf18329e9ff548b899e0587b1bd2affab4b1086ef280410f2d2420ab7f"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.29.0
rev = "82c9c80c11488858f1d3930f47ec9f335a566683"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.29.0
rev = "f5242d0415b35fe48344e83cfd60924725fed23d"

[dependencies.NftProtocol]
local = "../"

[addresses]
suitraders = "0x7e63f9bf18329e9ff548b899e0587b1bd2affab4b1086ef280410f2d2420ab7f"
