[package]
name = "gutenberg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.13"
thiserror = "1.0.37"
strfmt = "0.2.2"