Collection:
  name: "Suimarines"
  description: "A Unique NFT collection of Submarines on Sui"
  symbol: "SUIM"
  max_supply: 100
  receiver: "0x6c86ac4a796204ea09a87b6130db0c38263c1890"
  tags:
    - "Art"
    - "PFP"
  royalty_fee_bps: 100
  is_mutable: true
  data: "Some extra data"

NftType: "Unique"

Launchpad:
  market_type: "fixed_price"
  price: 1000
  whitelist: false